// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsckcllonhyffkntnikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzY2tjbGxvbmh5ZmZrbnRuaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODg1MzgsImV4cCI6MjA1ODU2NDUzOH0.eCZEhPMRJIt2pgU3s37ULWc2zmYUcYhA6P8_zSn1Chw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);